server:
  port: 8480

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/id3-notebook
    username: postgres
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  kafka:
    bootstrap-servers: localhost:9092

keycloak:
  auth-server-url: http://localhost:8080
  realm: ID3
  ssl-required: external
  resource: APP
  credentials:
    secret: rDJypDYBE4MUuzm0izQoAQEg09IAjhHc
  bearer-only: true
  use-resource-role-mappings: false